# RNN lab Johnny Depp vs Amber Heard

In [ ]:
FILE = 'drive/MyDrive/data/depp_vs_heard.txt'
USELESS = [':', '\"', '\'', '(', ')', ',', ':', '_', '/', '«', '–', '»', '[', ']', '„', '“', '&', '#', '`', '—', '-', '$', '’']
END_CHARS = ['?', ';', '!', '..', '…']
NUMBERS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
DOT = '.'
SPACE = ' '
NOTHING = ''

def load_data():
    text = []
    text_string_format = ''
    with open(FILE, encoding='UTF-8') as file:
        for line in file.readlines():
            line = line.strip()
            if (len(line) > 0) and (not line.isupper()):
                line = line.lower()
                for char in END_CHARS:
                    line = line.replace(char, DOT)
                for char in USELESS:
                    line = line.replace(char, SPACE)
                for char in NUMBERS:
                    line = line.replace(char, NOTHING)
                line = " ".join(line.split())
                lines = line.split(sep='.')
                for l in lines:
                    l = l.strip()
                    if len(l) != 0:
                        text.append(l + DOT)
                        text_string_format += l + DOT
    return text, text_string_format

In [ ]:
data, text_string_format = load_data()

In [ ]:
data

['johnny depp is still facing off against amber heard in a contentious legal battle where new information is continuously coming to light and new accusations are being leveled during each day of the trial.',
 'the defamation lawsuit which was first filed in kicked off on april with opening statements the following day that set the tone for the tumultuous courtroom battle that was about to commence.',
 'depps lawyers alleged that heard was fabricating claims to cast her ex husband in a bad light and heards lawyers accused depp of sexual violence during their marriage among other claims.',
 'the lawsuit itself kicked off nearly six years after heard first filed for divorce from depp on may after months of marriage citing irreconcilable differences.',
 'days later heard was granted a temporary restraining order against depp after an incident in which heard claims depp physically attacked her which depp has long denied.',
 'as part of their divorce which was finalized in january depp was o

In [ ]:
symbols = list(set(text_string_format))
symbols_len = len(symbols)

In [ ]:
symbols

['u',
 'y',
 'z',
 '.',
 's',
 'h',
 ' ',
 'f',
 'b',
 'a',
 'p',
 'o',
 'l',
 'g',
 't',
 'd',
 'x',
 'c',
 'r',
 'n',
 'j',
 'i',
 'q',
 'w',
 'v',
 'k',
 'e',
 'm']

In [ ]:
symbols_len

28

In [ ]:
from tqdm import tqdm # for %

def get_position(char, array):
    for i in range(len(array)):
        if array[i] == char:
            return i

def encode_char(char, symbols, number_of_symbols=28):
    one_hot = [0] * number_of_symbols
    ind = get_position(char, symbols)
    one_hot[ind] = 1
    return one_hot

def encode_line(line, symbols, number_of_symbols=28):
    sentence = []
    for char in line:
        sentence.append(encode_char(char, symbols, number_of_symbols))
    return sentence

def encode_all(ds, symbols, number_of_symbols=28):
    text = []
    for line in tqdm(ds):
        text.append(encode_line(line, symbols, number_of_symbols))
    return text

In [ ]:
data_one_hot = encode_all(data, symbols)

100%|██████████| 394/394 [00:00<00:00, 4508.17it/s]


In [ ]:
print(data_one_hot[0][0])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
import numpy as np

def divide_X_y(ds, window_size=20):
    X = []
    y = []
    for sentence in tqdm(ds):
        if len(sentence) <= window_size:
            continue
        for i in range(0, len(sentence) - window_size):
            cur_x = sentence[i:i + window_size]
            cur_y = sentence[i + window_size]
            X.append(cur_x)
            y.append(cur_y)
    return np.array(X), np.array(y)

In [ ]:
X, y = divide_X_y(data_one_hot)

100%|██████████| 394/394 [00:00<00:00, 4155.37it/s]


In [ ]:
print(X.shape, y.shape)

(29711, 20, 28) (29711, 28)


In [ ]:
print(X[0])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
print(y[0])

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


# LSTM

In [ ]:
import tensorflow as tf
lstm = tf.keras.models.Sequential()
lstm.add(tf.keras.layers.LSTM(128, input_shape=(20, symbols_len), dropout=0.2))
lstm.add(tf.keras.layers.Dense(symbols_len, activation='softmax'))
lstm.compile(loss='categorical_crossentropy', optimizer='adam')

In [ ]:
lstm.fit(X, y, epochs=10)

Epoch 1/10
929/929 [==============================] - 21s 21ms/step - loss: 2.6419
Epoch 2/10
929/929 [==============================] - 19s 20ms/step - loss: 2.3580
Epoch 3/10
929/929 [==============================] - 19s 21ms/step - loss: 2.2512
Epoch 4/10
929/929 [==============================] - 19s 20ms/step - loss: 2.1728
Epoch 5/10
929/929 [==============================] - 19s 20ms/step - loss: 2.1069
Epoch 6/10
929/929 [==============================] - 19s 21ms/step - loss: 2.0507
Epoch 7/10
929/929 [==============================] - 19s 21ms/step - loss: 2.0008
Epoch 8/10
929/929 [==============================] - 19s 20ms/step - loss: 1.9518
Epoch 9/10
929/929 [==============================] - 19s 21ms/step - loss: 1.9095
Epoch 10/10
929/929 [==============================] - 19s 21ms/step - loss: 1.8753


In [ ]:
def sample(predictions):
    predictions = np.log(predictions)
    exp_predictions = np.exp(predictions)
    predictions = exp_predictions / np.sum(exp_predictions)
    probabilities = np.random.multinomial(1, predictions, 1)
    return np.argmax(probabilities)

def lstm_predict(model, string, symbols):
    print(string, end="")
    string = encode_line(string, symbols)
    while True:
        prediction = model.predict(np.array([string]))
        # print(prediction[0])
        ind = sample(prediction[0])
        # ind = np.argmax(prediction[0])
        result = symbols[ind]
        print(result, end="")
        if result == DOT:
            break
        string.append(encode_char(result, symbols))
        string = string[1:]

In [ ]:
example = "johnny was damaged "
lstm_predict(lstm, example, symbols)

johnny was damaged by ctill at the actress thr ng laiss not on the coupiving text miotestorce.

# Markov chain

In [ ]:
def markov_build(text, length=10):
    transitions = dict()
    for i in tqdm(range(len(text) - length - 1)):
        cur = text[i : i + length]
        next = text[i + 1 : i + length + 1]
        if cur not in transitions:
            transitions[cur] = dict()
        if next not in transitions[cur]:
            transitions[cur][next] = 1
        else:
            transitions[cur][next] += 1
    return transitions

In [ ]:
trans = markov_build(text_string_format)

100%|██████████| 37278/37278 [00:00<00:00, 298772.21it/s]


In [ ]:
check_keys = list(trans.keys())
print(check_keys[0])
print(trans[check_keys[0]])

johnny dep
{'ohnny depp': 12}


In [ ]:
def count_probs(transitions):
    probabilities = dict()
    for key, value in transitions.items():
        all = 0
        probabilities[key] = dict()
        for k, v in value.items():
            all += v
        for k, v in value.items():
            probabilities[key][k] = v / all
    return probabilities

In [ ]:
probs = count_probs(trans)

In [ ]:
check_keys = list(probs.keys())
print(check_keys[0])
print(probs[check_keys[0]])

johnny dep
{'ohnny depp': 1.0}


In [ ]:
check_keys = list(probs.keys())
print(check_keys[2])
print(probs[check_keys[2]])

hnny depp 
{'nny depp i': 0.125, 'nny depp t': 0.375, 'nny depp a': 0.25, 'nny depp v': 0.25}


In [ ]:
def find_max(mapa):
    best_prob = 0
    best_res = ''
    for key, value in mapa.items():
        if value > best_prob:
            best_prob = value
            best_res = key
    return best_res

In [ ]:
def markov_predict(probabilities, string, length=10):
    print(string, end="")
    string = string[-length:]
    while True:
        if string not in probabilities:
            prediction = DOT
        else:
            prediction = find_max(probabilities[string])
        print(prediction[-1], end="")
        if prediction[-1] == DOT:
            return
        string += prediction
        string = string[-length:]

In [ ]:
example = "johnny depp "
markov_predict(probs, example)

johnny depp trial amber heard trial continues everything we know.